spring:
  application:
    name: api
  profiles:
    active: dev

  datasource:
    # 배포 환경에서는 환경변수로 주입
    url: ${BLOG_DB_URL}
    username: ${BLOG_DB_USERNAME}
    password: ${BLOG_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  # Flyway는 현재 compose에서 별도 컨테이너로 수행 중이라 앱에서는 비활성
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 9000
